
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'curso'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
seed-paths: ["seeds"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
asset-paths: ["assets"]


target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

require-dbt-version: ">=1.0.0"

quoting:
  database: false
  schema: false
  identifier: false




# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  +transient: false

  curso:
    staging:
      +materialized: view
      +database: |  
        {%- if  target.name == 'user_dev' -%} dev_silver_db_alumno10 
        {%- elif target.name == 'ci' -%} dev_silver_db_alumno10 
        {%- elif target.name == 'pro'-%} pro_silver_db_alumno10  
        {%- else -%} {{target.database}}_silver_db_alumno10
        {%- endif -%}
      tags: ['SILVER']
      google_sheets:
        +schema: google_sheets
      sql_server:
        +schema: sql_server
        base:
          +docs:
            node_color: "#C39BD3"
          tags: ['BASES']
        stages:
          +docs:
            node_color: "##5DADE2"
          tags: ['STAGES']
      others:
        +schema: others
    marts:
      +materialized: table
      +database: |  
        {%- if  target.name == 'user_dev' -%} dev_gold_db_alumno10  
        {%- elif target.name == 'ci' -%} dev_gold_db_alumno10 
        {%- elif target.name == 'pro'-%} pro_gold_db_alumno10 
        {%- else -%} {{target.database}}_gold_db_alumno10
        {%- endif -%}
      tags: ['GOLD']
      core:
        +schema: core
      distintas_areas:
        +schema: distintas_areas
      intermediate:
        +schema: intermediate
seeds:
  +transient: false
  +target_database: |  
        {%- if  target.name == 'user_dev' -%} dev_silver_db_alumno10 
        {%- elif target.name == 'ci' -%} dev_silver_db_alumno10 
        {%- elif target.name == 'pro'-%} pro_silver_db_alumno10  
        {%- else -%} {{target.database}}_silver_db_alumno10
        {%- endif -%}
  +target_schema: seeds

snapshots:
  +sql_header: "alter session set timezone = 'Europe/Madrid';alter session set week_start = 7;"
  +transient: false
  +target_database: |  
        {%- if  target.name == 'user_dev' -%} dev_silver_db_alumno10 
        {%- elif target.name == 'ci' -%} dev_silver_db_alumno10 
        {%- elif target.name == 'pro'-%} pro_silver_db_alumno10  
        {%- else -%} {{target.database}}_silver_db_alumno10
        {%- endif -%}
  +target_schema: snapshots

vars:
  "dbt_ml:audit_schema": "audit"
  "dbt_ml:audit_table": "ml_models"





